# Generated by Django 5.0.9 on 2024-12-10 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_is_pinned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='is_pinned',
        ),
    ]
